# Makefile for C++ Project

# Compiler
CC = g++

# Directories
SRC_DIR = src
INC_DIR = include
OBJ_DIR = obj
BIN_DIR = bin

# Source files
SRCS = $(wildcard $(SRC_DIR)/*.cpp)
OBJS = $(patsubst $(SRC_DIR)/%.cpp,$(OBJ_DIR)/%.o,$(SRCS))
INCS = -I$(INC_DIR)

# Compiler flags
CFLAGS = -Wall -g $(INCS)

# Executable
EXE = $(BIN_DIR)/my_program

# Targets
all: $(EXE)

$(EXE): $(OBJS)
	$(CC) -o $@ $(OBJS)

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ_DIR)/*.o $(EXE)

.PHONY: all clean
